### ISSUE TITLE
Integrate Validation into AWS Workflow

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/CHaMPAutomation#11]
As soon as @KellyMWhitehead is finished with the topo validation script, it needs to be integrated into the AWS workflow.

Only visits that pass this script are queued to have other engines run:

* Topo Metrics
* Site Properties
* Hydro Prep
* Habitat

## Questions we need to answer first:

- [ ] What percentage of visits pass?
- [ ] Are we ok with failed visits not getting Habitat, Hydo, Hydro Prep, etc. runs?

**Comment by MattReimer** [comment]
AWS is now on Production but is not integrated into the workflow yet. Still Only 41% of visits pass.

**Comment by MattReimer** [comment]
I'm going to call this task done for now as I think we decided not to chain processes together.
