### ISSUE TITLE
AEM Hookup and run for CHaMP Automation

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/CHaMPAutomation#15]
Because AEM uses a different API endpoints (which was unforseen) we need to make some non-trivial changes to be able to run AEM in the cloud. 

Expect 2-3 hours of work and 2-3 hours of testing

**Comment by MattReimer** [comment]
I've added an `aem` branch for this work

[Here's some initial work](52c39dbc21a642fd30c11eb15477ea701ea40483)

**Comment by volkcj** [comment]
can we set up a milestone date for the AWS-AEM hookup so that we can coordinate?  I'd like to get this in the queue before there's pressure.

**Comment by philipbaileynar** [comment]
This should be entirely on the back burner now. I've educated AEM how to run topo metrics as well as code and run their own custom metrics.

**Comment by MattReimer** [comment]
Yeah, just to chime in here: all the tools in `CHaMP_Metrics` now know how to go and get their own TopoData, regardless of what program they are so they can all be run outside the automation. 

This means you should be able to batch run any of our metric tools or validation without the automation.

**Comment by MattReimer** [comment]
I'm closing this issue for now. Let's re-open if we need to.
