### ISSUE TITLE
Site Props Fails when visit has no data

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/CHaMPAutomation#18]
Tried to run three visits that had previously not passed through Site Props:

```
QA/2014/Wenatchee/CBW05583-334443/VISIT_2663/RUN_SITEPROPS
QA/2014/Wenatchee/CBW05583-161963/VISIT_2553/RUN_SITEPROPS
QA/2014/Wenatchee/CBW05583-365227/VISIT_2554/RUN_SITEPROPS
```

These all failed because they have new 2017 visits that have not been sampled yet. The Site Props fails because a visit exists but there's no data available. Worker:

```
"[Create] STARTING: SiteProperties Run [0.00]s",
        "[STEP: 1: PREPARE] Prepare to download the local files [0.02]s",
        "[prepare] Preparing environment variables and paths [0.00]s",
        "[prepare] Created a directory for the project: /usr/tmp/siteprops/CBW05583-334443/GISLayers [0.00]s",
        "[prepare] Created Folder: /usr/tmp/siteprops/CBW05583-334443/SiteProperties [0.00]s",
        "[STEP: 2: GETALLVISITS] Find all the visits for this site in the API [0.02]s",
        "[getSecurityKey] Security Token API call success [0.40]s",
        "[APICaller] Success: get => 'sites/CBW05583334443' => [object Object] [0.28]s",
        "[downloadAllVisits] Found 2 visits for site: 'CBW05583-334443' [0.68]s",
        "[STEP: 3: S3DOWNLOADALLVISITS] Download the necessary Harold files from S3 [0.70]s",
        "[S3DownloadFolder] Successfully Downloaded \"QA/2014/Wenatchee/CBW05583-334443/VISIT_2663/Topo/GISLayers/Control_Points.dbf\" from S3 [1.18]s",
        "[S3DownloadFolder] Successfully Downloaded \"QA/2014/Wenatchee/CBW05583-334443/VISIT_2663/Topo/GISLayers/Control_Points.prj\" from S3 [1.09]s",
        "[S3DownloadFolder] Successfully Downloaded \"QA/2014/Wenatchee/CBW05583-334443/VISIT_2663/Topo/GISLayers/Control_Points.shp\" from S3 [0.99]s",
        "[S3DownloadFolder] Successfully Downloaded \"QA/2014/Wenatchee/CBW05583-334443/VISIT_2663/Topo/GISLayers/Control_Points.shp.xml\" from S3 [0.77]s",
        "[S3DownloadFolder] Successfully Downloaded \"QA/2014/Wenatchee/CBW05583-334443/VISIT_2663/Topo/GISLayers/Control_Points.shx\" from S3 [0.69]s",
        "[S3DownloadFolder] Successfully Downloaded \"QA/2014/Wenatchee/CBW05583-334443/VISIT_2663/Topo/GISLayers/Survey_Extent.dbf\" from S3 [0.65]s",
        "[S3DownloadFolder] Successfully Downloaded \"QA/2014/Wenatchee/CBW05583-334443/VISIT_2663/Topo/GISLayers/Survey_Extent.prj\" from S3 [0.50]s",
        "[S3DownloadFolder] Successfully Downloaded \"QA/2014/Wenatchee/CBW05583-334443/VISIT_2663/Topo/GISLayers/Survey_Extent.shp\" from S3 [0.46]s",
        "[S3DownloadFolder] Successfully Downloaded \"QA/2014/Wenatchee/CBW05583-334443/VISIT_2663/Topo/GISLayers/Survey_Extent.shp.xml\" from S3 [0.39]s",
        "[S3DownloadFolder] Successfully Downloaded \"QA/2014/Wenatchee/CBW05583-334443/VISIT_2663/Topo/GISLayers/Survey_Extent.shx\" from S3 [0.34]s",
        "[STEP: 4: createJSON] Create the JSON file based on everything we have downloaded [2.45]s",
        "[createJSONFile] WARNING: Missing layer data for visit: 2663",
        "[createJSONFile] WARNING: Missing layer data for visit: 4807",
        "[TASK ERROR] No visit data found for any of the 2 visits. [2.45]s",
        "[TASK ERROR] Task waterfall did not complete and will NOT be retried. [2.45]s"
```

This is a real world situation that needs to be fixed. Probably best handled if SiteProps proceeds when a visit has no files available. It should only bail if partial data are downloaded. Note, obviously this needs to handle if there's only a single visit with no files available.

**Comment by philipbaileynar** [comment]
The Site Props should be changed to detect when literally no data are downloaded for a visit. In this case, the visit should be ignored and site props continue (presuming there is more than one visit remaining that has data).

**Comment by MattReimer** [comment]
I'm going to do this in the NodeJS and then only pass on the visits that have data to the python code.

**Comment by philipbaileynar** [comment]
@MattReimer  I like this a lot better than Python handling zero file downloads. This feels like a more reliable solution. It can also be tweaked in future if we need to base the omission of visits on different visit property criteria from the API

**Comment by MattReimer** [comment]
just so we're super clear: I'm doing this by checking for `sampleDate== null` on each visit. This is easy to do. We can look at something more complex later if this doesn't fit the bill somehow.

**Comment by philipbaileynar** [comment]
@MattReimer I think that makes sense. I confess that I I haven't done a thorough analysis of the visit details properties to confirm that this is correct... but my sense is that visits without a sample date is correct.

Another way of doing this is to look for empty field files.

**Comment by MattReimer** [comment]
@volkcj The fix is in! 

Except all 3 remaining visits are missing `DEM.tif` so they all still failed

What's weird is that I'm seeing a `DEM.tfw` file but no `DEM.tif`. Weird no?

**Comment by MattReimer** [comment]
Ok. This is doing what it's supposed to. I'm closing the issue.

**Comment by volkcj** [comment]
@MattReimer -- Wenatchee 2011-2016 sync finished with sparkly new harold outputs from 6/29.  let er rip.
